Pill.Admin.webmvc/Controllers/CommandController.cs
using System.Web.Mvc;

namespace Pill.Admin.webmvc.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class CommandController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

Pill.Admin.webmvc/Controllers/SessionController.cs
using System.Web.Mvc;

namespace Pill.Admin.webmvc.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class SessionController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

Pill.Admin.webmvc/Controllers/UsersController.cs
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Pill.Admin.webmvc.Logics.Extensions;
using Pill.Admin.webmvc.Models;
using Pill.Admin.webmvc.Models.Users;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Pill.Admin.webmvc.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize(Roles = Roles.AdminRoleName)]
    public class UsersController : Controller
    {
        private ApplicationUserManager _userManager;

        /// <summary>
        /// 
        /// </summary>
        public UsersController()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="userManager"></param>
        public UsersController(ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        /// 
        /// </summary>
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage = message.TranslateToText();

            var currentUserId = User.Identity.GetUserId();
            var users = UserManager?.Users.Where(s => s.Id != currentUserId).ToList();
            return View(users);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Create() => View();

        /// <summary>
        /// 
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { SapCode = model.SapCode, UserName = model.SapCode, IsActive = model.IsActive };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await UserManager.AddToRoleAsync(user.Id, Roles.HubAdminRoleName);

                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
                return HttpNotFound();

            var model = new EditUserViewModel { Id = user.Id, SapCode = user.SapCode, IsActive = user.IsActive };
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = await UserManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.SapCode = model.SapCode;
                    user.UserName = model.SapCode;
                    user.IsActive = model.IsActive;

                    var result = await UserManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error);
                        }
                    }
                }
            }
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangePassword()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangeUserPasswordViewModel model)
        {
            if (!ModelState.IsValid || string.IsNullOrEmpty(model.Id))
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(model.Id, model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", new { Message = ManageMessageId.ChangePasswordSuccess });
            }
            AddErrors(result);
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="result"></param>
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public enum ManageMessageId
        {
            ChangePasswordSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
            Error
        }
    }
}

Pill.Admin.webmvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/Template/assets/images/favicon.png">
    <title>POS Admin</title>
    <!-- Custom CSS -->
    <link href="~/Template/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Template/dist/css/style.min.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!-- Preloader - style you can find in spinners.css -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- Main wrapper - style you can find in pages.scss -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
        <!-- Topbar header - style you can find in pages.scss -->
        <header class="topbar" data-navbarbg="skin6">
            <nav class="navbar top-navbar navbar-expand-md">
                <div class="navbar-header" data-logobg="skin6">
                    <!-- This is for the sidebar toggle which is visible on mobile only -->
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)">
                        <i class="ti-menu ti-close"></i>
                    </a>
                    <!-- Logo -->
                    <div class="navbar-brand">
                        <!-- Logo icon -->
                        <a href="@Url.Action("Index","Dashboard")">
                            <b class="logo-icon">
                                <img src="~/Template/assets/images/logo-icon.png" alt="homepage" class="dark-logo" />
                                <img src="~/Template/assets/images/logo-icon.png" alt="homepage" class="light-logo" />
                            </b>
                            <span class="logo-text">
                                <img src="~/Template/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                                <img src="~/Template/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
                            </span>
                        </a>
                    </div>
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
                       data-toggle="collapse" data-target="#navbarSupportedContent"
                       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="ti-more"></i>
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav float-left mr-auto ml-3 pl-1">
                    </ul>
                    <ul class="navbar-nav float-right">
                        <li class="nav-item dropdown">
                            @Html.Partial("_LoginPartial")
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="left-sidebar" data-sidebarbg="skin6">
            <div class="scroll-sidebar" data-sidebarbg="skin6">
                <nav class="sidebar-nav">
                    @Html.Partial("_MenuPartial");
                </nav>
            </div>
        </aside>
        <div class="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <!-- End Container fluid  -->
            <!-- footer -->
            <footer class="footer text-center text-muted">
                All Rights Reserved by PIll Group. Developed by <a href="https://pill.uz">Pill.uz</a>.
            </footer>
            <!-- End footer -->
        </div>
        <!-- End Page wrapper  -->
    </div>
    <!-- End Wrapper -->
    <!-- End Wrapper -->
    <!-- All Jquery -->
    <style>
        .users-card {
            display: inline-block;
            color: #000;
            text-decoration: none;
        }

            .users-card::after {
                content: '';
                display: block;
                width: 0;
                height: 2px;
                background: rgb(23, 118, 241);
                transition: width .3s;
            }

            .users-card:hover::after {
                width: 100%;
            }
    </style>

    <script src="~/Template/assets/libs/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/Template/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/Template/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/Template/dist/js/app-style-switcher.js"></script>
    <script src="~/Template/dist/js/feather.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="~/Template/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/Template/assets/extra-libs/sparkline/sparkline.js"></script>
    <!--Wave Effects -->
    <!-- themejs -->
    <!--Menu sidebar -->
    <script src="~/Template/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/Template/dist/js/custom.min.js"></script>
    <!--This page plugins -->
    <script src="~/Template/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Template/dist/js/pages/datatable/datatable-basic.init.js"></script>

    @RenderSection("scripts", required: false)
</body>

</html>

Pill.Admin.webmvc/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNet.Identity.Owin;

@if (User.Identity.IsAuthenticated)
{
    var userManager = Request.GetOwinContext().GetUserManager<ApplicationUserManager>();

    if (User.IsInRole(Pill.Admin.webmvc.Models.Roles.HubAdminRoleName) ||
        User.IsInRole(Pill.Admin.webmvc.Models.Roles.AdminRoleName))
    {
        <ul id="sidebarnav">
            <li class="sidebar-item">
                <a class="sidebar-link sidebar-link" href="@Url.Action("Index","Dashboard")"
                   aria-expanded="false">
                    <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
                </a>
            </li>
            <li class="list-divider"></li>
            <li class="sidebar-item">
                <a class="sidebar-link has-arrow" href="javascript:void(0)"
                   aria-expanded="false">
                    <i data-feather="file-text" class="feather-icon"></i><span class="hide-menu">Главный </span>
                </a>
                <ul aria-expanded="false" class="collapse  first-level base-level-line">
                    @if (User.IsInRole(Pill.Admin.webmvc.Models.Roles.AdminRoleName))
                    {
                        <li class="sidebar-item">
                            <a href="@Url.Action("Index","Users")" class="sidebar-link">
                                <span class="hide-menu">
                                    Админы
                                </span>
                            </a>
                        </li>
                    }
                    <li class="sidebar-item">
                        <a href="@Url.Action("Clients","Dashboard")" class="sidebar-link">
                            <span class="hide-menu">
                                Клиенты
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="@Url.Action("Index","Session")" class="sidebar-link">
                            <span class="hide-menu">
                                Сессии
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="@Url.Action("Index","Command")" class="sidebar-link">
                            <span class="hide-menu">
                                Запросы
                            </span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    }
}